-- Create the Accounts table
CREATE TABLE IF NOT EXISTS Accounts (
    ACCOUNTID INT PRIMARY KEY,
    BALANCE NUMERIC,
    CURRENCY VARCHAR(10)
);

-- Create the Transactions table
CREATE TABLE IF NOT EXISTS Transactions (
    TRANSACTIONID INT PRIMARY KEY,
    ACCOUNTID INTEGER,
    OTHERACCOUNTID INTEGER,
    AMOUNT INTEGER,
    CURRENCY VARCHAR(10),
    TYPE VARCHAR(10),
    TRANSACTIONDATE TIMESTAMP
);

INSERT INTO Accounts VALUES (1, 1000, 'EUR');
INSERT INTO Accounts VALUES (2, 500, 'EUR');
INSERT INTO Accounts VALUES (3, 2500, 'EUR');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 1, 2, 500, 'EUR', 'Debit', '2022-03-25 11:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 2, 3, 750, 'EUR', 'Credit', '2022-03-26 13:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 3, 4, 1000, 'EUR', 'Debit', '2022-03-27 15:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 4, 1, 1250, 'EUR', 'Credit', '2022-03-28 17:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 1, 3, 1500, 'EUR', 'Debit', '2022-03-29 19:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 2, 4, 1750, 'EUR', 'Credit', '2022-03-30 21:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 3, 1, 2000, 'EUR', 'Debit', '2022-03-31 23:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 4, 2, 2250, 'EUR', 'Credit', '2022-04-01 01:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 1, 4, 2500, 'EUR', 'Debit', '2022-04-02 03:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 2, 3, 2750, 'EUR', 'Credit', '2022-04-03 05:00:00');

INSERT INTO Transactions (TRANSACTIONID, ACCOUNTID, OTHERACCOUNTID, AMOUNT, CURRENCY, TYPE, TRANSACTIONDATE)
VALUES (NEXTVAL('transaction_sequence'), 3, 1, 3000, 'EUR', 'Debit', '2022-04-04 07:00:00');





